import org.gradle.api.JavaVersion

class Config {

    /**
     * appID
     */
    static applicationId = 'com.lsp.aucframe'
    static appName = 'AucFrameDemo'

    static compileSdkVersion = 29
    static buildToolsVersion = '29.0.3'
    static minSdkVersion = 18
    static targetSdkVersion = 29
    static versionCode = 1
    static versionName = '1.0.0'

    static sourceCompatibility = JavaVersion.VERSION_1_8
    static targetCompatibility = JavaVersion.VERSION_1_8

    static gradlePluginVersion = '3.5.0'
    static leakcanary_version = '2.1'

    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_mock               : new DepConfig(false, true , ":feature:mock"),
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_feature0_app       : new DepConfig(false, true , ":feature:feature0:app"),
            feature_feature0_pkg       : new DepConfig(true , true , ":feature:feature0:pkg"),
            feature_feature0_export    : new DepConfig(true , true , ":feature:feature0:export"),
            feature_feature1_app       : new DepConfig(false, true , ":feature:feature1:app"),
            feature_feature1_pkg       : new DepConfig(true , true , ":feature:feature1:pkg"),
            feature_feature1_export    : new DepConfig(true , true , ":feature:feature1:export"),
            lib_base                   : new DepConfig(true , true , ":lib:base"),
            lib_common                 : new DepConfig(true , true , ":lib:common"),
            /*Never delete this line*/
            plugin_gradle           : new DepConfig("com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_api              : new DepConfig(isApply: true, useLocal: false, pluginPath: "com.blankj:api-gradle-plugin:1.4", pluginId: "com.blankj.api"),
            plugin_bus              : new DepConfig(isApply: true, useLocal: false, pluginPath: "com.blankj:bus-gradle-plugin:2.6", pluginId: "com.blankj.bus"),

            android_annotation      : new DepConfig('androidx.annotation:annotation:1.1.0'),
            android_appcompat       : new DepConfig('androidx.appcompat:appcompat:1.2.0'),
            android_material        : new DepConfig('com.google.android.material:material:1.2.1'),
            android_constraintlayout: new DepConfig('androidx.constraintlayout:constraintlayout:2.0.4'),

            test_junit              : new DepConfig('junit:junit:4.13.1'),
            test_ext                : new DepConfig('androidx.test.ext:junit:1.1.2'),
            test_espresso           : new DepConfig('androidx.test.espresso:espresso-core:3.3.0'),

            leakcanary              : new DepConfig("com.squareup.leakcanary:leakcanary-android:$leakcanary_version"),

            support_multidex        : new DepConfig("com.android.support:multidex:1.0.2"),

            utilcode                : new DepConfig("com.blankj:utilcodex:1.30.5")

    ]
}